# Generated by Django 4.1.5 on 2023-07-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_expert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertreply',
            name='farmerquery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_expert.farmerquery'),
        ),
    ]
